CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    login varchar(100),
    email varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    req_user_id INTEGER REFERENCES users(user_id),
    resp_user_id INTEGER REFERENCES users(user_id),
    is_friend boolean DEFAULT 0,
    PRIMARY KEY (req_user_id, resp_user_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id integer PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpas (
    mpa_id integer PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (255) NOT NULL,
    description varchar (199),
    release_date date,
    duration integer,
    mpa_id integer REFERENCES mpas(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id integer REFERENCES films(film_id),
    user_id integer REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id integer REFERENCES films(film_id),
    genre_id integer REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
);